name: Go Releaser

on:
    push:
        tags:
            - "*"
    workflow_call:


permissions:
    contents: write

jobs:
    tag:
        runs-on: ubuntu-latest

    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: RunGoReleaser
              uses: goreleaser/goreleaser-action@v5
              with:
                  distribution: goreleaser
                  version: "~> v1"
                  args: release --clean
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
