name: goreleaser

on:
    push:
        tags:
            - "*"

permissions:
    contents: write

jobs:
    tag:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Get latest tag
              id: get_latest_tag
              run: |
                  LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                  echo "Latest tag: $LATEST_TAG"
                  echo "::set-output name=tag::$LATEST_TAG"

            - name: Increment version
              id: increment_version
              run: |
                  TAG=${{ steps.get_latest_tag.outputs.tag }}
                  echo "Current tag is $TAG"
                  IFS='.' read -r -a VERSION_PARTS <<< "$TAG"
                  MAJOR=${VERSION_PARTS[0]}
                  MINOR=${VERSION_PARTS[1]}
                  PATCH=${VERSION_PARTS[2]}
                  PATCH=$((PATCH + 1))
                  NEW_TAG="$MAJOR.$MINOR.$PATCH"
                  echo "New tag is $NEW_TAG"
                  echo "::set-output name=new_tag::$NEW_TAG"

            - name: Create new tag
              run: |
                  git config --global user.email "you@example.com"
                  git config --global user.name "Your Name"
                  NEW_TAG=${{ steps.increment_version.outputs.new_tag }}
                  git tag $NEW_TAG
                  git push origin $NEW_TAG
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: RunGoReleaser
              uses: goreleaser/goreleaser-action@v5
              with:
                  distribution: goreleaser
                  version: "~> v1"
                  args: release --clean
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
