name: Tag new release

on:
    push:
        branches:
            - main
        tags-ignore:
            - "*"

jobs:
    update-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
      
            - name: Configure Git
              run: |
                AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
                AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')

                git config user.email "$AUTHOR_EMAIL"
                git config user.name "$AUTHOR_NAME"
            - name: Create new tag
              id: tag_version
              run: |
                  NEW_TAG = "v$(cat VERSION)"
                  git tag -a $NEW_TAG -m "Release $NEW_TAG"
                  git push origin $NEW_TAG
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
