on:
    push:
        branches:
            - main
        tags-ignore:
            - "*"

jobs:
    update-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: RunGoReleaser
              uses: goreleaser/goreleaser-action@v5
              with:
                  distribution: goreleaser
                  version: "~> v1"
                  args: release --clean

            - name: Create environment variable from version
              id: tag_version
              run: |
                  git tag -a v$(cat VERSION)
                  git push origin v$(cat VERSION)
